### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by natiginfo** [reaktor/tips-for-ppl-who-want-to-learn#3]
In the line, where it says "Programming in Scala free pdf", the link is broken: http://ccfit.nsu.ru/~den/Scala/programming_in_scala_2nd.pdf

**Comment by raimohanska** [comment]
Replaced book links with links to official sources. If you wish to download free pdf's, you can most likely find them by googling. Buying the real thing is of course what I recommend.

**Comment by natiginfo** [comment]
Thanks!
