### ISSUE TITLE
Missing "mega list" in IOS section

### ISSUE THREAD

**Issue by 5c0r** [reaktor/tips-for-ppl-who-want-to-learn#6]
Hello Reaktorians,

A very good list of tips, I have always enjoyed reading them . Kudos 👍 .

By the way, it would be nice to know what are the "mega list" for learning IOS from here:
https://github.com/reaktor/tips-for-ppl-who-want-to-learn/blob/master/README.md#ios

Thanks again 😄,
Tri

**Comment by WickedLynx** [comment]
Thanks for pointing this out, Tri. We have updated the section with the link :)
